import { City } from '../types';

export const CITIES: City[] = [
  // ─── NORTH INDIA ─────────────────────────────────────────────────────────
  {
    id: 'delhi',
    name: 'New Delhi',
    state: 'Delhi',
    region: 'North',
    costIndex: 'High',
    description: "India's bustling capital blending Mughal grandeur, colonial architecture, and modern skyline. Explore ancient forts, UNESCO sites, vibrant bazaars, and world-class cuisine.",
    image: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Red Fort', 'India Gate', 'Qutub Minar', 'Chandni Chowk', 'Humayun Tomb'],
    lat: 28.6139, lng: 77.2090,
    keywords: ['delhi', 'capital', 'mughal', 'monument', 'old delhi']
  },
  {
    id: 'agra',
    name: 'Agra',
    state: 'Uttar Pradesh',
    region: 'North',
    costIndex: 'Medium',
    description: 'Home to the eternal wonder — the Taj Mahal. Agra preserves Mughal magnificence in its forts, palaces, and marble craftsmanship on the banks of the Yamuna.',
    image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Taj Mahal', 'Agra Fort', 'Fatehpur Sikri', 'Mehtab Bagh', 'Mughal Cuisine'],
    lat: 27.1767, lng: 78.0081,
    keywords: ['taj mahal', 'mughal', 'marble', 'yamuna', 'heritage']
  },
  {
    id: 'jaipur',
    name: 'Jaipur',
    state: 'Rajasthan',
    region: 'North',
    costIndex: 'Medium',
    description: "The Pink City dazzles with its rose-hued palaces, majestic amber forts, vibrant bazaars of textiles and gems, and legendary Rajasthani hospitality.",
    image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Amber Fort', 'City Palace', 'Hawa Mahal', 'Jantar Mantar', 'Johri Bazaar'],
    lat: 26.9124, lng: 75.7873,
    keywords: ['pink city', 'rajasthan', 'amber', 'palace', 'heritage']
  },
  {
    id: 'jodhpur',
    name: 'Jodhpur',
    state: 'Rajasthan',
    region: 'North',
    costIndex: 'Medium',
    description: "The Blue City, dominated by the imposing Mehrangarh Fort. Cobalt-painted houses, arid landscapes, royal cuisine, and an atmospheric old city wait to be explored.",
    image: 'https://images.unsplash.com/photo-1602301462048-f2e7d27fbfe1?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Mehrangarh Fort', 'Umaid Bhawan Palace', 'Jaswant Thada', 'Ghanta Ghar', 'Mirchi Bada'],
    lat: 26.2389, lng: 73.0243,
    keywords: ['blue city', 'rajasthan', 'fort', 'desert', 'royal']
  },
  {
    id: 'udaipur',
    name: 'Udaipur',
    state: 'Rajasthan',
    region: 'North',
    costIndex: 'High',
    description: "City of Lakes and Romance — floating palaces on shimmering Pichola Lake, ornate havelis, and a backdrop of Aravalli Hills make Udaipur India's most romantic city.",
    image: 'https://images.unsplash.com/photo-1577703614219-a8a91b7ec668?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Lake Palace', 'City Palace', 'Fateh Sagar Lake', 'Jagdish Temple', 'Lake Pichola Boat Ride'],
    lat: 24.5854, lng: 73.7125,
    keywords: ['lake city', 'romantic', 'rajasthan', 'palace', 'lakes']
  },
  {
    id: 'pushkar',
    name: 'Pushkar',
    state: 'Rajasthan',
    region: 'North',
    costIndex: 'Low',
    description: 'A sacred pilgrimage town encircling the holy Pushkar Lake, famous for its only Brahma temple, ghats, annual camel fair, and a vibrant bohemian traveller culture.',
    image: 'https://images.unsplash.com/photo-1585136917228-8c0e6dd5a993?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Brahma Temple', 'Pushkar Lake Ghats', 'Camel Fair', 'Sunset Point', 'Israeli Cafes'],
    lat: 26.4891, lng: 74.5512,
    keywords: ['pilgrimage', 'holy lake', 'camel fair', 'brahma', 'ghats']
  },
  {
    id: 'jaisalmer',
    name: 'Jaisalmer',
    state: 'Rajasthan',
    region: 'North',
    costIndex: 'Medium',
    description: 'The Golden City rising from the Thar Desert — a living fort of golden sandstone, intricately carved havelis, camel safaris through rolling dunes, and star-lit desert camps.',
    image: 'https://images.unsplash.com/photo-1586861256632-1eb856df2dbc?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Jaisalmer Fort', 'Sam Sand Dunes', 'Patwon Ki Haveli', 'Camel Safari', 'Desert Night Camp'],
    lat: 26.9157, lng: 70.9083,
    keywords: ['golden city', 'thar desert', 'dunes', 'camel', 'fort']
  },
  {
    id: 'bikaner',
    name: 'Bikaner',
    state: 'Rajasthan',
    region: 'North',
    costIndex: 'Low',
    description: 'Famous for its colossal Junagarh Fort, heritage havelis, the quirky Karni Mata rat temple, and the finest Bikaneri bhujia snacks in India.',
    image: 'https://images.unsplash.com/photo-1650969046027-79cd3fa86a7b?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Junagarh Fort', 'Karni Mata Temple', 'National Research Centre on Camel', 'Bikaneri Bhujia', 'Rampuria Havelis'],
    lat: 28.0229, lng: 73.3119,
    keywords: ['rajasthan', 'fort', 'camel', 'heritage', 'bikaner']
  },
  {
    id: 'mount-abu',
    name: 'Mount Abu',
    state: 'Rajasthan',
    region: 'North',
    costIndex: 'Medium',
    description: "Rajasthan's only hill station, set among dense forests with the breathtaking Dilwara Jain temples carved in marble, Nakki Lake, and cool breeze at Guru Shikhar peak.",
    image: 'https://images.unsplash.com/photo-1594302011648-75e5d25fb91f?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Dilwara Jain Temples', 'Nakki Lake', 'Guru Shikhar', 'Sunset Point', 'Achalgarh Fort'],
    lat: 24.5926, lng: 72.7156,
    keywords: ['hill station', 'rajasthan', 'jain temple', 'marble', 'forest']
  },
  {
    id: 'amritsar',
    name: 'Amritsar',
    state: 'Punjab',
    region: 'North',
    costIndex: 'Low',
    description: 'Home to the sacred Golden Temple — the spiritual and cultural heart of Sikhism. The Wagah Border Beating Retreat ceremony and Amritsari kulcha are iconic experiences.',
    image: 'https://images.unsplash.com/photo-1609946860441-a51ffed7db1e?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Golden Temple', 'Wagah Border', 'Jallianwala Bagh', 'Amritsari Kulcha', 'Heritage Walk'],
    lat: 31.6340, lng: 74.8723,
    keywords: ['golden temple', 'sikh', 'punjab', 'wagah', 'gurdwara']
  },
  {
    id: 'chandigarh',
    name: 'Chandigarh',
    state: 'Chandigarh',
    region: 'North',
    costIndex: 'Medium',
    description: "India's first planned city by Le Corbusier — immaculate gardens, the whimsical Rock Garden, Sukhna Lake, and a vibrant café culture make it uniquely charming.",
    image: 'https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Rock Garden', 'Rose Garden', 'Sukhna Lake', 'Capitol Complex', 'Elante Mall'],
    lat: 30.7333, lng: 76.7794,
    keywords: ['planned city', 'rock garden', 'punjab', 'modern', 'chandigarh']
  },
  {
    id: 'shimla',
    name: 'Shimla',
    state: 'Himachal Pradesh',
    region: 'North',
    costIndex: 'Medium',
    description: 'Former summer capital of British India, nestled in pine-clad Himalayan ridges. The Mall Road, colonial architecture, toy train, and apple orchards define its charm.',
    image: 'https://images.unsplash.com/photo-1597900121060-db2caf44debc?auto=format&fit=crop&w=800&q=80',
    popularFor: ['The Mall Road', 'Jakhu Temple', 'Toy Train (Kalka-Shimla)', 'Chadwick Falls', 'Christ Church'],
    lat: 31.1048, lng: 77.1734,
    keywords: ['hill station', 'himachal', 'colonial', 'toy train', 'pine']
  },
  {
    id: 'manali',
    name: 'Manali',
    state: 'Himachal Pradesh',
    region: 'North',
    costIndex: 'Medium',
    description: "A Himalayan adventure capital in the Beas River valley — trekking, skiing, Rohtang Pass snowfields, Buddhist monasteries, and Old Manali's hippie cafe culture.",
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Rohtang Pass', 'Solang Valley', 'Hadimba Temple', 'Old Manali Cafes', 'Beas River Rafting'],
    lat: 32.2396, lng: 77.1887,
    keywords: ['adventure', 'snow', 'himalaya', 'skiing', 'trek']
  },
  {
    id: 'dharamshala',
    name: 'Dharamshala',
    state: 'Himachal Pradesh',
    region: 'North',
    costIndex: 'Low',
    description: 'Home of the Dalai Lama and the Tibetan government-in-exile. McLeod Ganj offers Tibetan culture, meditation retreats, stunning Dhauladhar views, and trekking trails.',
    image: 'https://images.unsplash.com/photo-1615212698139-b2c1e1c98a05?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Namgyal Monastery', 'Bhagsu Waterfall', 'Triund Trek', 'Tibetan Food', 'Meditation Centres'],
    lat: 32.2190, lng: 76.3234,
    keywords: ['mcleod ganj', 'dalai lama', 'tibetan', 'trek', 'monastery']
  },
  {
    id: 'dalhousie',
    name: 'Dalhousie',
    state: 'Himachal Pradesh',
    region: 'North',
    costIndex: 'Low',
    description: 'A quaint Victorian hill station spread over five hills with panoramic Himalayan views, colonial churches, Khajjiar meadows, and Chamba valley charm.',
    image: 'https://images.unsplash.com/photo-1625921342049-f89b8e24d2e0?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Khajjiar Lake', 'Panchpula', 'Subhash Baoli', 'Satdhara Falls', 'Tibetan Market'],
    lat: 32.5389, lng: 75.9627,
    keywords: ['hill station', 'khajjiar', 'colonial', 'himachal', 'views']
  },
  {
    id: 'srinagar',
    name: 'Srinagar',
    state: 'Jammu & Kashmir',
    region: 'North',
    costIndex: 'Medium',
    description: "Summer capital of J&K, famed for its magical Dal Lake houseboats, Mughal gardens, the floating vegetable market, and some of the world's finest saffron and handicrafts.",
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Dal Lake Houseboat', 'Shikara Ride', 'Mughal Gardens', 'Hazratbal Shrine', 'Local Wazwan Cuisine'],
    lat: 34.0837, lng: 74.7973,
    keywords: ['kashmir', 'dal lake', 'houseboat', 'saffron', 'mughal gardens']
  },
  {
    id: 'gulmarg',
    name: 'Gulmarg',
    state: 'Jammu & Kashmir',
    region: 'North',
    costIndex: 'High',
    description: "Asia's highest gondola, world-class ski slopes, and meadows carpeted with wildflowers — Gulmarg is Kashmir's premier alpine adventure destination.",
    image: 'https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Gondola Cable Car', 'Skiing', 'Golf Course', 'Alpather Lake', 'Snow Sledging'],
    lat: 34.0484, lng: 74.3805,
    keywords: ['ski resort', 'snow', 'kashmir', 'gondola', 'alpine']
  },
  {
    id: 'pahalgam',
    name: 'Pahalgam',
    state: 'Jammu & Kashmir',
    region: 'North',
    costIndex: 'Medium',
    description: "The Valley of Shepherds at the confluence of Lidder streams, base camp for the Amarnath Yatra, and gateway to stunning Betaab Valley, Aru, and Chandanwari meadows.",
    image: 'https://images.unsplash.com/photo-1630403716617-2f1ad09c98ac?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Betaab Valley', 'Aru Valley', 'Baisaran Meadow', 'Lidder River Fishing', 'Chandanwari'],
    lat: 34.0160, lng: 75.3150,
    keywords: ['kashmir', 'valley', 'amarnath', 'meadows', 'trek']
  },
  {
    id: 'leh',
    name: 'Leh',
    state: 'Ladakh',
    region: 'North',
    costIndex: 'High',
    description: "The high-altitude capital of Ladakh at 3500m — ancient monasteries, lunar landscapes, turquoise lakes (Pangong, Tso Moriri), and the world's highest motorable roads.",
    image: 'https://images.unsplash.com/photo-1513094775335-7f3bc4e3e0e8?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Pangong Tso', 'Thiksey Monastery', 'Nubra Valley Camels', 'Khardung La Pass', 'Leh Palace'],
    lat: 34.1526, lng: 77.5771,
    keywords: ['ladakh', 'high altitude', 'pangong', 'monastery', 'himalaya']
  },
  {
    id: 'rishikesh',
    name: 'Rishikesh',
    state: 'Uttarakhand',
    region: 'North',
    costIndex: 'Low',
    description: 'Yoga capital of the world at the foothills of the Himalayas. Sacred Ganges ghats, ashrams, white-water rafting on the Ganges, and the iconic Lakshman Jhula bridge.',
    image: 'https://images.unsplash.com/photo-1591014880942-440d9d0d1491?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Ganges Rafting', 'Lakshman Jhula', 'Yoga Ashrams', 'Ganga Aarti', 'Bungee Jumping'],
    lat: 30.0869, lng: 78.2676,
    keywords: ['yoga', 'ganges', 'raft', 'ashram', 'spiritual', 'adventure']
  },
  {
    id: 'haridwar',
    name: 'Haridwar',
    state: 'Uttarakhand',
    region: 'North',
    costIndex: 'Low',
    description: "Gateway to the Gods at the foothills of the Himalayas. Har Ki Pauri's Ganga Aarti ceremony, Kumbh Mela pilgrimage, and the eternal Ganges bathing ghats.",
    image: 'https://images.unsplash.com/photo-1605649487212-47bdab064df8?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Har Ki Pauri', 'Ganga Aarti at Dusk', 'Mansa Devi Temple', 'Chandi Devi Ropeway', 'Kumbh Mela Ghats'],
    lat: 29.9457, lng: 78.1642,
    keywords: ['ganga aarti', 'pilgrimage', 'kumbh', 'ganges', 'spiritual']
  },
  {
    id: 'mussoorie',
    name: 'Mussoorie',
    state: 'Uttarakhand',
    region: 'North',
    costIndex: 'Medium',
    description: "Queen of the Hills — a charming Himalayan resort town with Mall Road promenades, Kempty Falls, Landour village, and panoramic Himalayan views.",
    image: 'https://images.unsplash.com/photo-1615212698139-b2c1e1c98a04?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Gun Hill', 'Kempty Falls', 'Mall Road', 'Landour Bakehouse', 'Char Dukan Cafes'],
    lat: 30.4598, lng: 78.0644,
    keywords: ['hill station', 'uttarakhand', 'kempty falls', 'queen of hills', 'himalaya']
  },
  {
    id: 'nainital',
    name: 'Nainital',
    state: 'Uttarakhand',
    region: 'North',
    costIndex: 'Medium',
    description: 'A Himalayan lake district town centred around the emerald Naini Lake, with boating, ropeway rides to Naina Peak, and charming colonial bungalows.',
    image: 'https://images.unsplash.com/photo-1597134049062-6b0cda5dbd99?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Naini Lake Boating', 'Naina Devi Temple', 'Snow View Point', 'Eco Cave Gardens', 'Mall Road'],
    lat: 29.3919, lng: 79.4542,
    keywords: ['lake', 'uttarakhand', 'hill station', 'boat', 'himalaya']
  },
  {
    id: 'dehradun',
    name: 'Dehradun',
    state: 'Uttarakhand',
    region: 'North',
    costIndex: 'Low',
    description: 'Gateway to Uttarakhand in the Doon Valley — surrounded by Himalayan forests, Sahastradhara waterfalls, Robber\'s Cave, the prestigious RIMC, and excellent food culture.',
    image: 'https://images.unsplash.com/photo-1625921342049-f89b8e24d2e3?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Sahastradhara', "Robber's Cave", 'Tapkeshwar Temple', 'Clock Tower', 'Forest Research Institute'],
    lat: 30.3165, lng: 78.0322,
    keywords: ['doon valley', 'gateway', 'forest', 'waterfall', 'uttarakhand']
  },
  {
    id: 'varanasi',
    name: 'Varanasi',
    state: 'Uttar Pradesh',
    region: 'North',
    costIndex: 'Low',
    description: "One of the world's oldest living cities on the sacred Ganges — 84 ghats, dawn boat rides, cremation ceremonies at Manikarnika, Kashi Vishwanath temple, and Banarasi silk.",
    image: 'https://images.unsplash.com/photo-1561361058-c24cecae35ca?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Dashashwamedh Ghat Aarti', 'Dawn Boat Ride', 'Kashi Vishwanath Temple', 'Sarnath Stupa', 'Banarasi Silk'],
    lat: 25.3176, lng: 82.9739,
    keywords: ['banaras', 'ganges', 'ghat', 'spiritual', 'oldest city', 'aarti']
  },
  {
    id: 'lucknow',
    name: 'Lucknow',
    state: 'Uttar Pradesh',
    region: 'North',
    costIndex: 'Low',
    description: 'City of Nawabs — exquisite Mughal-era architecture, the finest Awadhi cuisine (kebabs, biryani), chikankari embroidery, and refined Urdu culture.',
    image: 'https://images.unsplash.com/photo-1617160702001-7bd58d9b8b37?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Bara Imambara', 'Rumi Darwaza', 'Tunday Kababi', 'Hazratganj Walk', 'Chikankari Shopping'],
    lat: 26.8467, lng: 80.9462,
    keywords: ['nawab', 'awadhi', 'kebab', 'biryani', 'chikan', 'heritage']
  },
  {
    id: 'ayodhya',
    name: 'Ayodhya',
    state: 'Uttar Pradesh',
    region: 'North',
    costIndex: 'Low',
    description: "Ram Janmabhoomi — the sacred birthplace of Lord Ram. The newly consecrated Ram Mandir, Sarayu ghats, Hanuman Garhi, and Kanak Bhawan attract millions of pilgrims.",
    image: 'https://images.unsplash.com/photo-1617160702001-7bd58d9b8b38?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Ram Mandir', 'Hanuman Garhi', 'Sarayu Ghat', 'Kanak Bhawan', 'Nageshwarnath Temple'],
    lat: 26.7922, lng: 82.1942,
    keywords: ['ram mandir', 'pilgrimage', 'ram janmabhoomi', 'sarayu', 'hindu']
  },
  {
    id: 'mathura',
    name: 'Mathura',
    state: 'Uttar Pradesh',
    region: 'North',
    costIndex: 'Low',
    description: "Birthplace of Lord Krishna, with 25 sacred ghats along the Yamuna, the majestic Shri Krishna Janmabhoomi temple, and enchanting Holi celebrations.",
    image: 'https://images.unsplash.com/photo-1617160702001-7bd58d9b8b39?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Krishna Janmabhoomi Temple', 'Vishram Ghat', 'Dwarkadhish Temple', 'Vrindavan', 'Holi Festival'],
    lat: 27.4924, lng: 77.6737,
    keywords: ['krishna', 'brij', 'holi', 'vrindavan', 'yamuna', 'pilgrimage']
  },
  {
    id: 'prayagraj',
    name: 'Prayagraj',
    state: 'Uttar Pradesh',
    region: 'North',
    costIndex: 'Low',
    description: 'The Triveni Sangam — the holy confluence of Ganga, Yamuna, and mythical Saraswati rivers. Host of the Kumbh Mela, Allahabad Fort, and the Anand Bhawan museum.',
    image: 'https://images.unsplash.com/photo-1617160702001-7bd58d9b8b40?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Triveni Sangam', 'Kumbh Mela', 'Allahabad Fort', 'Anand Bhawan', 'Sangam Boat Ride'],
    lat: 25.4358, lng: 81.8463,
    keywords: ['allahabad', 'sangam', 'kumbh mela', 'triveni', 'ganges']
  },
  {
    id: 'khajuraho',
    name: 'Khajuraho',
    state: 'Madhya Pradesh',
    region: 'North',
    costIndex: 'Low',
    description: 'UNESCO World Heritage temples famous for their intricate erotic sculptures and Nagara architecture. The light-and-sound show and nearby Panna National Park are must-sees.',
    image: 'https://images.unsplash.com/photo-1566158939485-7e6c421df69e?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Western Temple Group', 'Eastern Temple Group', 'Archaeological Museum', 'Light & Sound Show', 'Panna Tiger Reserve'],
    lat: 24.8318, lng: 79.9199,
    keywords: ['temples', 'unesco', 'sculpture', 'heritage', 'chandela']
  },

  // ─── WEST INDIA ──────────────────────────────────────────────────────────
  {
    id: 'mumbai',
    name: 'Mumbai',
    state: 'Maharashtra',
    region: 'West',
    costIndex: 'High',
    description: "India's Maximum City and financial capital — the Gateway of India, Marine Drive's sparkling Queen's Necklace, Bollywood, street food, and the global metropolis energy.",
    image: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Gateway of India', 'Marine Drive', 'Elephanta Caves', 'Dharavi Tour', 'Bollywood Experience'],
    lat: 19.0760, lng: 72.8777,
    keywords: ['maximum city', 'bollywood', 'financial hub', 'marine drive', 'gateway']
  },
  {
    id: 'pune',
    name: 'Pune',
    state: 'Maharashtra',
    region: 'West',
    costIndex: 'Medium',
    description: "Oxford of the East with a vibrant youth culture, excellent food scene, OSHO ashram, Shaniwar Wada Peshwa palace, and a perfect base for Sahyadri trekking.",
    image: 'https://images.unsplash.com/photo-1611348586804-61bf6c080437?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Shaniwar Wada', 'Aga Khan Palace', 'OSHO International', 'Koregaon Park Cafes', 'Sinhagad Fort'],
    lat: 18.5204, lng: 73.8567,
    keywords: ['oxford of east', 'peshwa', 'osho', 'cafe culture', 'sahyadri']
  },
  {
    id: 'nashik',
    name: 'Nashik',
    state: 'Maharashtra',
    region: 'West',
    costIndex: 'Low',
    description: "The wine capital of India set in the godly Godavari valley — vineyards, Sula Winery tours, the Trimbakeshwar Shiva temple, and Kumbh Mela on the Godavari ghats.",
    image: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Sula Vineyard', 'Trimbakeshwar Temple', 'Pandav Leni Caves', 'Godavari Ghats', 'Shirdi Sai Baba'],
    lat: 19.9975, lng: 73.7898,
    keywords: ['wine', 'vineyard', 'kumbh', 'shiva', 'godavari', 'shirdi']
  },
  {
    id: 'aurangabad',
    name: 'Aurangabad',
    state: 'Maharashtra',
    region: 'West',
    costIndex: 'Medium',
    description: 'Gateway to the Ajanta and Ellora Caves UNESCO World Heritage Sites — a crossroads of Hindu, Buddhist, and Mughal heritage with the Bibi Ka Maqbara "mini Taj Mahal".',
    image: 'https://images.unsplash.com/photo-1566158939485-7e6c421df69b?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Ellora Caves', 'Ajanta Caves', 'Bibi Ka Maqbara', 'Daulatabad Fort', 'Silk Weaving'],
    lat: 19.8762, lng: 75.3433,
    keywords: ['ajanta', 'ellora', 'caves', 'unesco', 'mughal', 'sambhajinagar']
  },
  {
    id: 'lonavala',
    name: 'Lonavala',
    state: 'Maharashtra',
    region: 'West',
    costIndex: 'Low',
    description: 'A popular hill resort in the Sahyadri range between Mumbai and Pune — misty monsoon waterfalls, Bhushi Dam, Karla and Bhaja Caves, and famous chikki sweets.',
    image: 'https://images.unsplash.com/photo-1611348586804-61bf6c080436?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Bhushi Dam', 'Tiger Point', 'Karla Caves', 'Shooting Point', 'Chikki Shopping'],
    lat: 18.7481, lng: 73.4072,
    keywords: ['hill station', 'monsoon', 'waterfall', 'sahyadri', 'weekend']
  },
  {
    id: 'mahabaleshwar',
    name: 'Mahabaleshwar',
    state: 'Maharashtra',
    region: 'West',
    costIndex: 'Medium',
    description: 'Maharashtra\'s highest hill station with strawberry farms, overlooks into three valleys, Venna Lake boating, and Pratapgad Fort — the site of Shivaji\'s famous duel.',
    image: 'https://images.unsplash.com/photo-1611348586804-61bf6c080435?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Arthur Seat', 'Venna Lake', 'Strawberry Farms', 'Pratapgad Fort', 'Wilson Point Sunrise'],
    lat: 17.9307, lng: 73.6477,
    keywords: ['strawberry', 'hill station', 'sahyadri', 'shivaji', 'valley']
  },
  {
    id: 'goa',
    name: 'Goa',
    state: 'Goa',
    region: 'West',
    costIndex: 'High',
    description: "India's beach paradise — Portuguese colonial churches, golden beaches from Baga to Palolem, legendary seafood, vibrant nightlife, water sports, and a laid-back coastal spirit.",
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Baga Beach', 'Fort Aguada', 'Old Goa Churches', 'Dudhsagar Falls', 'Goa Seafood'],
    lat: 15.2993, lng: 74.1240,
    keywords: ['beach', 'portuguese', 'seafood', 'nightlife', 'coastal', 'party']
  },
  {
    id: 'ahmedabad',
    name: 'Ahmedabad',
    state: 'Gujarat',
    region: 'West',
    costIndex: 'Medium',
    description: 'UNESCO World Heritage city — intricately carved havelis, the Sabarmati Ashram of Mahatma Gandhi, Calico Museum of Textiles, and the vibrant street food of Manek Chowk.',
    image: 'https://images.unsplash.com/photo-1611348586804-61bf6c080434?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Sabarmati Ashram', 'Sidi Saiyyed Mosque', 'Manek Chowk Night Market', 'Adalaj Stepwell', 'Textile Museum'],
    lat: 23.0225, lng: 72.5714,
    keywords: ['gandhi', 'heritage city', 'stepwell', 'textile', 'gujarat', 'pols']
  },
  {
    id: 'vadodara',
    name: 'Vadodara',
    state: 'Gujarat',
    region: 'West',
    costIndex: 'Low',
    description: "Baroda — the cultured city of the Gaekwads with Laxmi Vilas Palace (four times the size of Buckingham Palace), Sayaji Bagh zoo, MSU's fine arts tradition, and Navratri grandeur.",
    image: 'https://images.unsplash.com/photo-1611348586804-61bf6c080433?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Laxmi Vilas Palace', 'Sayaji Bagh', 'Baroda Museum', 'Champaner-Pavagadh', 'Navratri Garba'],
    lat: 22.3072, lng: 73.1812,
    keywords: ['baroda', 'palace', 'gaekwad', 'navratri', 'gujarat', 'champaner']
  },
  {
    id: 'bhuj',
    name: 'Bhuj',
    state: 'Gujarat',
    region: 'West',
    costIndex: 'Low',
    description: "Gateway to the Rann of Kutch — vast white salt desert, Harappan site of Dholavira, intricate Kutchi craft traditions (embroidery, bandhani, rogan art), and Rann Utsav festival.",
    image: 'https://images.unsplash.com/photo-1611348586804-61bf6c080432?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Great Rann of Kutch', 'Dholavira', 'Aina Mahal', 'Rann Utsav', 'Kutchi Handicrafts'],
    lat: 23.2420, lng: 69.6669,
    keywords: ['rann of kutch', 'white desert', 'kutch', 'handicraft', 'tribal']
  },
  {
    id: 'dwarka',
    name: 'Dwarka',
    state: 'Gujarat',
    region: 'West',
    costIndex: 'Low',
    description: "One of the Char Dham pilgrimage sites — the Dwarkadhish Temple of Lord Krishna stands at the tip of the Saurashtra peninsula where the Gomti River meets the Arabian Sea.",
    image: 'https://images.unsplash.com/photo-1617160702001-7bd58d9b8b41?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Dwarkadhish Temple', 'Gomti Ghat', 'Bet Dwarka Island', 'Nageshwar Jyotirlinga', 'Rukmini Temple'],
    lat: 22.2394, lng: 68.9678,
    keywords: ['char dham', 'krishna', 'pilgrimage', 'jyotirlinga', 'gujarat']
  },
  {
    id: 'surat',
    name: 'Surat',
    state: 'Gujarat',
    region: 'West',
    costIndex: 'Low',
    description: "India's diamond cutting capital and textile hub — a foodie's paradise with 100+ types of snacks, the Dutch Garden, and fabulous Surati snacks like locho and ponk.",
    image: 'https://images.unsplash.com/photo-1611348586804-61bf6c080431?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Diamond Market', 'Surat Castle', 'Dutch Cemetery', 'Dumas Beach', 'Locho Street Food'],
    lat: 21.1702, lng: 72.8311,
    keywords: ['diamond', 'textile', 'street food', 'locho', 'gujarat']
  },

  // ─── SOUTH INDIA ─────────────────────────────────────────────────────────
  {
    id: 'bengaluru',
    name: 'Bengaluru',
    state: 'Karnataka',
    region: 'South',
    costIndex: 'High',
    description: "India's Silicon Valley and pub capital — vibrant craft beer culture, lush parks, Bangalore Palace, excellent restaurant scene, and gateway to Karnataka's incredible heritage.",
    image: 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Lalbagh Gardens', 'Bangalore Palace', 'Cubbon Park', 'Vidhana Soudha', 'MG Road Pubs'],
    lat: 12.9716, lng: 77.5946,
    keywords: ['bangalore', 'silicon valley', 'pub', 'tech city', 'garden city']
  },
  {
    id: 'mysuru',
    name: 'Mysuru',
    state: 'Karnataka',
    region: 'South',
    costIndex: 'Medium',
    description: "The City of Palaces — the grandest Mysore Palace illuminated by 100,000 bulbs, Chamundi Hills, silk and sandalwood bazaars, and India's best-organized Dasara celebrations.",
    image: 'https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Mysore Palace', 'Chamundi Hills', 'Devaraja Market', 'Brindavan Gardens', 'Mysore Silk Shopping'],
    lat: 12.2958, lng: 76.6394,
    keywords: ['mysore', 'palace', 'dasara', 'silk', 'sandalwood', 'chamundi']
  },
  {
    id: 'hampi',
    name: 'Hampi',
    state: 'Karnataka',
    region: 'South',
    costIndex: 'Low',
    description: 'A surreal UNESCO World Heritage landscape of ancient Vijayanagara Empire ruins — massive boulder terrain, the Vittala Temple stone chariot, Virupaksha Temple, and sunset on Hemakuta Hill.',
    image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74221?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Vittala Temple', 'Virupaksha Temple', 'Stone Chariot', 'Hampi Bazaar', 'Coracle Ride'],
    lat: 15.3350, lng: 76.4600,
    keywords: ['ruins', 'vijayanagara', 'boulders', 'unesco', 'ancient', 'temple']
  },
  {
    id: 'coorg',
    name: 'Coorg (Madikeri)',
    state: 'Karnataka',
    region: 'South',
    costIndex: 'Medium',
    description: "Scotland of India — rolling coffee and tea plantations, Cauvery River rafting, Abbey Falls, Namdroling Buddhist Monastery (Golden Temple), and Kodava warrior culture.",
    image: 'https://images.unsplash.com/photo-1596178060671-7a9f35d6f562?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Coffee Plantation Tour', 'Abbey Falls', 'Raja Seat', 'Namdroling Monastery', 'Cauvery Rafting'],
    lat: 12.4244, lng: 75.7382,
    keywords: ['coffee', 'plantation', 'coorg', 'kodagu', 'waterfall', 'buddhist']
  },
  {
    id: 'chikmagalur',
    name: 'Chikmagalur',
    state: 'Karnataka',
    region: 'South',
    costIndex: 'Low',
    description: "Where coffee was first introduced to India — misty Mullayanagiri peak (highest in Karnataka), Bhadra Wildlife Sanctuary, cascading Hebbe Falls, and coffee-estate homestays.",
    image: 'https://images.unsplash.com/photo-1596178060671-7a9f35d6f563?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Mullayanagiri Peak Trek', 'Bhadra Wildlife Sanctuary', 'Hebbe Falls', 'Coffee Estate Tour', 'Kemmangundi Viewpoint'],
    lat: 13.3161, lng: 75.7720,
    keywords: ['coffee origin', 'trek', 'peak', 'wildlife', 'waterfall']
  },
  {
    id: 'gokarna',
    name: 'Gokarna',
    state: 'Karnataka',
    region: 'South',
    costIndex: 'Low',
    description: 'A sacred coastal town with pristine beaches hidden behind rocky headlands — Om Beach, Half Moon Beach, and Kudle Beach draw pilgrims and backpackers alike.',
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f3?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Om Beach', 'Mahabaleshwar Temple', 'Half Moon Beach', 'Kudle Beach', 'Beach Trekking'],
    lat: 14.5479, lng: 74.3188,
    keywords: ['beach', 'pilgrimage', 'backpacker', 'coastal', 'shiva']
  },
  {
    id: 'hyderabad',
    name: 'Hyderabad',
    state: 'Telangana',
    region: 'South',
    costIndex: 'High',
    description: "City of Pearls — Golconda Fort, the Charminar bazaar, Nizam's architectural legacy, and the world-renowned Hyderabadi Dum Biryani. Also India's burgeoning tech city.",
    image: 'https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Charminar', 'Golconda Fort', 'Hussain Sagar', 'Biryani at Paradise', 'Chowmahalla Palace'],
    lat: 17.3850, lng: 78.4867,
    keywords: ['biryani', 'nizams', 'golconda', 'pearls', 'telangana']
  },
  {
    id: 'visakhapatnam',
    name: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    region: 'South',
    costIndex: 'Medium',
    description: "Vizag — a jewel of the Eastern Ghats meeting the Bay of Bengal. INS Kursura submarine museum, Araku Valley scenic train, RK Beach, and Borra Caves stalactites.",
    image: 'https://images.unsplash.com/photo-1611348586804-61bf6c080430?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Araku Valley', 'Borra Caves', 'INS Kursura Submarine Museum', 'RK Beach', 'Simhachalam Temple'],
    lat: 17.6868, lng: 83.2185,
    keywords: ['vizag', 'beach', 'araku valley', 'caves', 'eastern ghats']
  },
  {
    id: 'tirupati',
    name: 'Tirupati',
    state: 'Andhra Pradesh',
    region: 'South',
    costIndex: 'Low',
    description: "The richest temple on earth — Tirumala Venkateswara Temple atop the Tirumala Hills draws millions of devotees making it the world's most visited pilgrimage destination.",
    image: 'https://images.unsplash.com/photo-1617160702001-7bd58d9b8b42?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Tirumala Venkateswara Temple', 'Tirumala Hills', 'Srivari Padalu', 'Kapila Teertham', 'Silathoranam Rock Arch'],
    lat: 13.6288, lng: 79.4192,
    keywords: ['venkateswara', 'balaji', 'pilgrimage', 'temple', 'richest temple']
  },
  {
    id: 'chennai',
    name: 'Chennai',
    state: 'Tamil Nadu',
    region: 'South',
    costIndex: 'Medium',
    description: "Gateway to South India with the world's longest urban beach Marina, Kapaleeshwarar Temple, colonial Fort St. George, Carnatic music traditions, and amazing filter coffee.",
    image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Marina Beach', 'Kapaleeshwarar Temple', 'Mahabalipuram', 'Filter Coffee Culture', 'Carnatic Music'],
    lat: 13.0827, lng: 80.2707,
    keywords: ['madras', 'marina beach', 'dravidian', 'carnatic', 'filter coffee']
  },
  {
    id: 'mahabalipuram',
    name: 'Mahabalipuram',
    state: 'Tamil Nadu',
    region: 'South',
    costIndex: 'Low',
    description: "UNESCO shore temples carved by Pallava kings in granite — Shore Temple at sunrise, Arjuna's Penance rock relief, Five Rathas chariots, and a thriving stone-carving tradition.",
    image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74222?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Shore Temple', "Arjuna's Penance", 'Five Rathas', 'Stone Carving Workshops', 'Tiger Cave'],
    lat: 12.6269, lng: 80.1927,
    keywords: ['pallava', 'shore temple', 'unesco', 'carved', 'mamallapuram']
  },
  {
    id: 'pondicherry',
    name: 'Pondicherry',
    state: 'Puducherry',
    region: 'South',
    costIndex: 'Low',
    description: "A French colonial enclave on the Coromandel Coast — bright-painted maison coloniales, the Auroville utopian community, Sri Aurobindo Ashram, and fine French cafes.",
    image: 'https://images.unsplash.com/photo-1601778083811-6b5e1d4b0e75?auto=format&fit=crop&w=800&q=80',
    popularFor: ['French Quarter Walk', 'Auroville Matrimandir', 'Sri Aurobindo Ashram', 'Promenade Beach', 'French Cafes'],
    lat: 11.9416, lng: 79.8083,
    keywords: ['french', 'colonial', 'auroville', 'ashram', 'puducherry']
  },
  {
    id: 'madurai',
    name: 'Madurai',
    state: 'Tamil Nadu',
    region: 'South',
    costIndex: 'Low',
    description: "Temple City of South India — the colossal Meenakshi Amman Temple with 14 gopurams and thousands of sculptures, night bazaars, jasmine garlands, and Chettinad cuisine.",
    image: 'https://images.unsplash.com/photo-1596178060671-7a9f35d6f564?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Meenakshi Amman Temple', 'Tirumalai Nayak Palace', 'Vandiyur Mariamman Teppakulam', 'Night Bazaar', 'Chettinad Food'],
    lat: 9.9252, lng: 78.1198,
    keywords: ['meenakshi', 'temple city', 'gopuram', 'chettinad', 'jasmine']
  },
  {
    id: 'ooty',
    name: 'Ooty (Udhagamandalam)',
    state: 'Tamil Nadu',
    region: 'South',
    costIndex: 'Medium',
    description: "Queen of the Nilgiris — UNESCO-listed Nilgiri Mountain Railway (toy train), Doddabetta Peak, botanical gardens with a 2,000-year-old fossil tree, and emerald tea estates.",
    image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74223?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Nilgiri Mountain Railway', 'Doddabetta Peak', 'Botanical Gardens', 'Ooty Lake', 'Tea Estate Tour'],
    lat: 11.4102, lng: 76.6950,
    keywords: ['nilgiri', 'toy train', 'tea', 'hill station', 'botanical']
  },
  {
    id: 'kodaikanal',
    name: 'Kodaikanal',
    state: 'Tamil Nadu',
    region: 'South',
    costIndex: 'Medium',
    description: "Princess of Hill Stations — a star-shaped lake, fragrant pine forests, Coaker's Walk cliff path, Silver Cascade waterfall, and excellent cycling trails in the Palani Hills.",
    image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74224?auto=format&fit=crop&w=800&q=80',
    popularFor: ["Kodaikanal Lake", "Coaker's Walk", 'Silver Cascade Falls', 'Pillar Rocks', 'Cycling Trails'],
    lat: 10.2381, lng: 77.4892,
    keywords: ['princess hill station', 'lake', 'pine forest', 'coakers walk', 'palani']
  },
  {
    id: 'rameswaram',
    name: 'Rameswaram',
    state: 'Tamil Nadu',
    region: 'South',
    costIndex: 'Low',
    description: "A Char Dham pilgrimage island connected by the Pamban Bridge — Ramanathaswamy Temple with the longest corridor in India, 22 sacred wells, and the Adam's Bridge shoal.",
    image: 'https://images.unsplash.com/photo-1617160702001-7bd58d9b8b43?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Ramanathaswamy Temple', 'Pamban Bridge', '22 Sacred Wells Bath', 'Dhanushkodi Ruins', "Adam's Bridge"],
    lat: 9.2876, lng: 79.3129,
    keywords: ['char dham', 'pilgrimage', 'pamban bridge', 'ramanathaswamy', 'dhanushkodi']
  },
  {
    id: 'kanyakumari',
    name: 'Kanyakumari',
    state: 'Tamil Nadu',
    region: 'South',
    costIndex: 'Low',
    description: "The southernmost tip of India where three seas meet. Sunrise and sunset viewpoints where Indian Ocean, Arabian Sea, and Bay of Bengal converge, plus the Vivekananda Rock Memorial.",
    image: 'https://images.unsplash.com/photo-1611348586804-61bf6c080429?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Vivekananda Rock Memorial', 'Thiruvalluvar Statue', 'Sunrise & Sunset', 'Kumari Amman Temple', 'Three Seas Convergence'],
    lat: 8.0883, lng: 77.5385,
    keywords: ['southernmost tip', 'three seas', 'sunrise sunset', 'vivekananda', 'cape comorin']
  },
  {
    id: 'kochi',
    name: 'Kochi',
    state: 'Kerala',
    region: 'South',
    costIndex: 'Medium',
    description: "Queen of the Arabian Sea — Chinese fishing nets at Fort Kochi, Jewish Quarter antiques, spice markets of Mattancherry, kathakali performances, and the backwater gateway.",
    image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Chinese Fishing Nets', 'Fort Kochi Heritage Walk', 'Kathakali Performance', 'Mattancherry Spice Market', 'Jew Town'],
    lat: 9.9312, lng: 76.2673,
    keywords: ['cochin', 'kerala', 'backwaters', 'spice', 'chinese fishing nets', 'fort kochi']
  },
  {
    id: 'munnar',
    name: 'Munnar',
    state: 'Kerala',
    region: 'South',
    costIndex: 'Medium',
    description: "Where the Western Ghats meet the clouds — endless emerald tea gardens, Eravikulam National Park Nilgiri Tahr, misty Anamudi summit, and a cool escape from the plains.",
    image: 'https://images.unsplash.com/photo-1594826558895-fa92a8a6dd35?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Tea Estate Tour', 'Eravikulam National Park', 'Anamudi Peak', 'Mattupetty Dam', 'Rose Garden'],
    lat: 10.0889, lng: 77.0595,
    keywords: ['tea gardens', 'western ghats', 'kerala', 'trekking', 'nilgiri']
  },
  {
    id: 'alleppey',
    name: 'Alleppey (Alappuzha)',
    state: 'Kerala',
    region: 'South',
    costIndex: 'Medium',
    description: "Venice of the East — overnight houseboat cruises through palm-fringed backwater canals, snake boat races, lush paddy fields, and the Vembanad Lake sunsets.",
    image: 'https://images.unsplash.com/photo-1569096651661-820d59a91524?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Houseboat Backwater Cruise', 'Vembanad Lake', 'Snake Boat Race (Nehru Trophy)', 'Marari Beach', 'Ayurvedic Spa'],
    lat: 9.4981, lng: 76.3388,
    keywords: ['venice of east', 'houseboat', 'backwaters', 'snake boat race', 'canals']
  },
  {
    id: 'varkala',
    name: 'Varkala',
    state: 'Kerala',
    region: 'South',
    costIndex: 'Low',
    description: "Kerala's clifftop beach gem — Papanasam Beach at the base of dramatic laterite cliffs, the Janardhana Swamy Temple, natural mineral springs, and a chilled backpacker vibe.",
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f4?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Papanasam Cliff Beach', 'Janardhana Swami Temple', 'Cliff Walk', 'Mineral Springs', 'Ayurvedic Treatments'],
    lat: 8.7379, lng: 76.7163,
    keywords: ['cliff beach', 'backpacker', 'kerala', 'mineral spring', 'temple']
  },
  {
    id: 'thekkady',
    name: 'Thekkady (Periyar)',
    state: 'Kerala',
    region: 'South',
    costIndex: 'Medium',
    description: "Periyar Wildlife Sanctuary — bamboo rafting on Periyar Lake amid jungle elephants, Kerala cooking classes in a spice garden, and tribal forest treks led by indigenous guides.",
    image: 'https://images.unsplash.com/photo-1569096651661-820d59a91525?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Periyar Lake Boat Safari', 'Elephant Spotting', 'Spice Plantation Tour', 'Bamboo Rafting', 'Tribal Eco-trek'],
    lat: 9.5872, lng: 77.1667,
    keywords: ['periyar', 'wildlife', 'elephant', 'spice', 'jungle', 'bamboo rafting']
  },
  {
    id: 'wayanad',
    name: 'Wayanad',
    state: 'Kerala',
    region: 'South',
    costIndex: 'Low',
    description: "Kerala's highland paradise — Edakkal Caves with prehistoric paintings, Chembra Peak trek, Pookode Lake, tea and coffee plantation stays, and Kuruva Island in the Kabini river.",
    image: 'https://images.unsplash.com/photo-1598977895613-4c0e394ad2b9?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Edakkal Caves', 'Chembra Peak Trek', 'Pookode Lake', 'Plantation Homestay', 'Kuruva Island'],
    lat: 11.6854, lng: 76.1320,
    keywords: ['kerala highlands', 'caves', 'trek', 'plantation', 'wildlife']
  },

  // ─── EAST & CENTRAL INDIA ────────────────────────────────────────────────
  {
    id: 'kolkata',
    name: 'Kolkata',
    state: 'West Bengal',
    region: 'East',
    costIndex: 'Low',
    description: "City of Joy and cultural capital of India — Victoria Memorial, Howrah Bridge, tram rides, adda culture, Bengali sweets (mishti doi, rasgolla), and the grand Durga Puja.",
    image: 'https://images.unsplash.com/photo-1558431382-27e303142255?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Victoria Memorial', 'Howrah Bridge', 'Dakshineswar Temple', 'Kumartuli Potters Quarter', 'Durga Puja'],
    lat: 22.5726, lng: 88.3639,
    keywords: ['city of joy', 'bengali', 'durga puja', 'tram', 'intellectual', 'sweets']
  },
  {
    id: 'darjeeling',
    name: 'Darjeeling',
    state: 'West Bengal',
    region: 'East',
    costIndex: 'Medium',
    description: "Queen of the Himalayas — Kanchenjunga sunrise from Tiger Hill, UNESCO Darjeeling Himalayan Railway toy train, the world's finest tea gardens, and Tibetan Buddhist monasteries.",
    image: 'https://images.unsplash.com/photo-1566002088516-39af0f9bf2f3?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Tiger Hill Sunrise', 'UNESCO Toy Train', 'Tea Garden Visit', 'Batasia Loop', 'Happy Valley Tea Estate'],
    lat: 27.0360, lng: 88.2627,
    keywords: ['tea', 'toy train', 'kanchenjunga', 'himalaya', 'tiger hill']
  },
  {
    id: 'gangtok',
    name: 'Gangtok',
    state: 'Sikkim',
    region: 'East',
    costIndex: 'Medium',
    description: "Sikkim's capital in the clouds with Kanchenjunga views from MG Marg, Rumtek Monastery, Nathu La mountain pass to China, and pristine Tsomgo alpine lake.",
    image: 'https://images.unsplash.com/photo-1596178060671-7a9f35d6f565?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Rumtek Monastery', 'Nathu La Pass', 'Tsomgo Lake', 'MG Road', 'Sikkim Organic Food'],
    lat: 27.3314, lng: 88.6138,
    keywords: ['sikkim', 'nathu la', 'monastery', 'kanchenjunga', 'tsomgo']
  },
  {
    id: 'shillong',
    name: 'Shillong',
    state: 'Meghalaya',
    region: 'East',
    costIndex: 'Low',
    description: "Scotland of the East — living root bridges, Cherrapunji's record rainfall, Ward's Lake, vibrant rock music scene, Khasi tribal culture, and the world's cleanest village Mawlynnong.",
    image: 'https://images.unsplash.com/photo-1597900121060-db2caf44debd?auto=format&fit=crop&w=800&q=80',
    popularFor: ["Ward's Lake", 'Elephant Falls', 'Police Bazaar', 'Cherrapunji Day Trip', 'Living Root Bridges'],
    lat: 25.5788, lng: 91.8933,
    keywords: ['scotland of east', 'meghalaya', 'cherrapunji', 'living root bridge', 'khasi']
  },
  {
    id: 'cherrapunji',
    name: 'Cherrapunji',
    state: 'Meghalaya',
    region: 'East',
    costIndex: 'Low',
    description: "Wettest place on Earth — double-decker living root bridges woven by Khasi tribals, Nohkalikai (tallest plunge waterfall), rainbow viewpoints, and limestone cave kayaking.",
    image: 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Double Decker Root Bridge', 'Nohkalikai Falls', 'Rainbow Falls', 'Mawsmai Limestone Cave', 'Eco Park'],
    lat: 25.2902, lng: 91.7226,
    keywords: ['root bridge', 'waterfall', 'meghalaya', 'khasi', 'wettest', 'sohra']
  },
  {
    id: 'guwahati',
    name: 'Guwahati',
    state: 'Assam',
    region: 'East',
    costIndex: 'Low',
    description: "Gateway to North-East India — the Kamakhya Tantric temple, Brahmaputra River boat rides to Umananda Island, Kaziranga rhino reserve access, and Assam silk & tea.",
    image: 'https://images.unsplash.com/photo-1597900121060-db2caf44debe?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Kamakhya Temple', 'Umananda Island', 'Brahmaputra Cruise', 'Kaziranga Day Trip', 'Assam Tea'],
    lat: 26.1445, lng: 91.7362,
    keywords: ['assam', 'kamakhya', 'brahmaputra', 'kaziranga', 'gateway northeast']
  },
  {
    id: 'tawang',
    name: 'Tawang',
    state: 'Arunachal Pradesh',
    region: 'East',
    costIndex: 'Medium',
    description: "India's highest monastery at 3048m — the majestic Tawang Monastery, Sela Pass frozen lake, Nuranang Waterfall (Jang Falls), and the Tawang War Memorial for the 1962 battle.",
    image: 'https://images.unsplash.com/photo-1625921342049-f89b8e24d2e1?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Tawang Monastery', 'Sela Pass', 'Nuranang Falls', 'War Memorial', 'Madhuri Lake'],
    lat: 27.5860, lng: 91.8600,
    keywords: ['monastery', 'buddhist', 'sela pass', 'arunachal', 'war memorial']
  },
  {
    id: 'kohima',
    name: 'Kohima',
    state: 'Nagaland',
    region: 'East',
    costIndex: 'Low',
    description: "Capital of the Nagas — the Kohima War Cemetery commemorating the 'Stalingrad of the East' WWII battle, Hornbill Festival of tribal culture, and Naga morung architecture.",
    image: 'https://images.unsplash.com/photo-1625921342049-f89b8e24d2e2?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Kohima War Cemetery', 'Hornbill Festival', 'Nagaland State Museum', 'Dzükou Valley Trek', 'Naga Village'],
    lat: 25.6751, lng: 94.1086,
    keywords: ['nagaland', 'hornbill festival', 'war cemetery', 'tribal', 'naga']
  },
  {
    id: 'puri',
    name: 'Puri',
    state: 'Odisha',
    region: 'East',
    costIndex: 'Low',
    description: "One of the four Char Dhams — the giant Jagannath Rath Yatra chariot festival, a magnificent ocean beach, the Konark Sun Temple 35km away, and the Pattachitra painting tradition.",
    image: 'https://images.unsplash.com/photo-1617160702001-7bd58d9b8b44?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Jagannath Temple', 'Rath Yatra', 'Puri Beach', 'Konark Sun Temple', 'Pattachitra Paintings'],
    lat: 19.8134, lng: 85.8312,
    keywords: ['jagannath', 'char dham', 'rath yatra', 'odisha', 'beach', 'konark']
  },
  {
    id: 'bhubaneswar',
    name: 'Bhubaneswar',
    state: 'Odisha',
    region: 'East',
    costIndex: 'Low',
    description: "Temple City of India — over 700 medieval temples including Lingaraja, the Udayagiri & Khandagiri rock-cut caves, Dhauli Buddhist Peace Pagoda, and excellent odissi dance.",
    image: 'https://images.unsplash.com/photo-1617160702001-7bd58d9b8b45?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Lingaraja Temple', 'Udayagiri Caves', 'Dhauligiri Shanti Stupa', 'Mukteshwar Temple', 'Nandankanan Zoo'],
    lat: 20.2961, lng: 85.8245,
    keywords: ['temple city', 'odisha', 'lingaraja', 'caves', 'odissi', 'buddhist']
  },
  {
    id: 'bodh-gaya',
    name: 'Bodh Gaya',
    state: 'Bihar',
    region: 'East',
    costIndex: 'Low',
    description: "The most sacred Buddhist site on earth — the Bodhi Tree under which the Buddha attained enlightenment, Mahabodhi Temple (UNESCO), and dozens of international monasteries.",
    image: 'https://images.unsplash.com/photo-1566002088516-39af0f9bf2f4?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Mahabodhi Temple (UNESCO)', 'Bodhi Tree', 'Buddha Statue', 'Japanese & Thai Temples', 'Meditation Retreat'],
    lat: 24.6959, lng: 84.9914,
    keywords: ['buddhist', 'bodhi tree', 'mahabodhi', 'enlightenment', 'pilgrimage', 'bihar']
  },
  {
    id: 'bhopal',
    name: 'Bhopal',
    state: 'Madhya Pradesh',
    region: 'East',
    costIndex: 'Low',
    description: "City of Lakes — the upper and lower Bhopal lakes, excellent Tribal Museum (Rashtriya Manav Sangrahalaya), Bhimbetka UNESCO rock shelters, and Sanchi Buddhist stupa.",
    image: 'https://images.unsplash.com/photo-1617160702001-7bd58d9b8b46?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Sanchi Stupa (UNESCO)', 'Bhimbetka Rock Shelters', 'Upper Lake Boat', 'Tribal Museum', 'Taj ul Masajid'],
    lat: 23.2599, lng: 77.4126,
    keywords: ['madhya pradesh', 'lakes', 'sanchi', 'bhimbetka', 'tribal', 'stupa']
  },
  {
    id: 'indore',
    name: 'Indore',
    state: 'Madhya Pradesh',
    region: 'East',
    costIndex: 'Low',
    description: "India's cleanest city (5 times in a row) and food capital of MP — Sarafa Bazaar night food street, Rajwada Palace, Khajrana Ganesh Temple, and fabulous poha-jalebi breakfasts.",
    image: 'https://images.unsplash.com/photo-1617160702001-7bd58d9b8b47?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Sarafa Bazaar Night Food', 'Rajwada Palace', 'Lal Bagh Palace', 'Kanch Mandir', 'Poha Jalebi Breakfast'],
    lat: 22.7196, lng: 75.8577,
    keywords: ['cleanest city', 'food capital', 'sarafa bazaar', 'rajwada', 'madhya pradesh']
  },
  {
    id: 'ujjain',
    name: 'Ujjain',
    state: 'Madhya Pradesh',
    region: 'East',
    costIndex: 'Low',
    description: "Kshipra River holy city and home of the Mahakaleshwar Jyotirlinga — one of the 12 Jyotirlingas with the auspicious Bhasma Aarti, Kumbh Mela venue, and Kal Bhairav temple.",
    image: 'https://images.unsplash.com/photo-1617160702001-7bd58d9b8b48?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Mahakaleshwar Temple', 'Bhasma Aarti', 'Kshipra Ghats', 'Kal Bhairav Temple', 'Kumbh Mela'],
    lat: 23.1765, lng: 75.7885,
    keywords: ['jyotirlinga', 'mahakaleshwar', 'shiva', 'kumbh', 'bhasma aarti']
  },
  {
    id: 'nagpur',
    name: 'Nagpur',
    state: 'Maharashtra',
    region: 'East',
    costIndex: 'Low',
    description: "Orange City in the exact geographic centre of India — Deekshabhoomi Buddhist stupa (Ambedkar's conversion site), Ramtek Fort temple, Pench Tiger Reserve, and juicy Nagpuri oranges.",
    image: 'https://images.unsplash.com/photo-1617160702001-7bd58d9b8b49?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Deekshabhoomi', 'Ramtek Fort', 'Pench Tiger Reserve', 'Futala Lake', 'Nagpuri Orange Market'],
    lat: 21.1458, lng: 79.0882,
    keywords: ['orange city', 'central india', 'tiger reserve', 'buddhist', 'deekshabhoomi']
  },
  {
    id: 'port-blair',
    name: 'Port Blair',
    state: 'Andaman & Nicobar Islands',
    region: 'East',
    costIndex: 'High',
    description: "Gateway to the Andaman Islands — the historic Cellular Jail, Radhanagar Beach (Asia's Best), pristine coral reefs, WW2 Japanese bunkers, and emerald Havelock Island.",
    image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Cellular Jail', 'Radhanagar Beach', 'Havelock Island', 'Scuba Diving', 'Neil Island Snorkeling'],
    lat: 11.6234, lng: 92.7265,
    keywords: ['andaman', 'cellular jail', 'beach', 'scuba diving', 'coral reef', 'islands']
  },
];

export default CITIES;
