import { IndianCityData } from '../types';

export const INDIAN_CITIES: IndianCityData[] = [
  // ─── TIER 1 / MAJOR METROS ──────────────────────────────────────────────────
  {
    name: 'New Delhi',
    state: 'Delhi (NCT)',
    lat: 28.6139,
    lng: 77.2090,
    description: 'Capital territory blending historical Mughal monuments with modern avenues.',
    popularAttractions: ['Red Fort', 'Qutub Minar', 'Humayun\'s Tomb', 'India Gate', 'Lotus Temple', 'Chandni Chowk'],
    image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9946?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Mumbai',
    state: 'Maharashtra',
    lat: 18.9220,
    lng: 72.8347,
    description: 'The bustling City of Dreams on the Arabian Sea coast.',
    popularAttractions: ['Gateway of India', 'Marine Drive', 'Elephanta Caves', 'Chhatrapati Shivaji Terminus', 'Juhu Beach'],
    image: 'https://images.unsplash.com/photo-1529253355930-ddbe423a2ac7?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Bengaluru (Bangalore)',
    state: 'Karnataka',
    lat: 12.9716,
    lng: 77.5946,
    description: 'The Garden City and Silicon Valley of India with pleasant year-round weather.',
    popularAttractions: ['Lalbagh Botanical Garden', 'Bangalore Palace', 'Cubbon Park', 'Vidhana Soudha', 'Tipu Sultan\'s Summer Palace'],
    image: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Kolkata',
    state: 'West Bengal',
    lat: 22.5726,
    lng: 88.3639,
    description: 'The City of Joy and cultural capital of India along the Hooghly River.',
    popularAttractions: ['Victoria Memorial', 'Howrah Bridge', 'Dakshineswar Kali Temple', 'Indian Museum', 'Park Street'],
    image: 'https://images.unsplash.com/photo-1536421469767-80559bb6f5e1?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Chennai',
    state: 'Tamil Nadu',
    lat: 13.0827,
    lng: 80.2707,
    description: 'Gateway to South India known for classical Carnatic music, Dravidian temples, and Marina Beach.',
    popularAttractions: ['Marina Beach', 'Kapaleeshwarar Temple', 'Fort St. George', 'San Thome Basilica', 'Government Museum'],
    image: 'https://images.unsplash.com/photo-1596439953453-c7745d531498?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Hyderabad',
    state: 'Telangana',
    lat: 17.3850,
    lng: 78.4867,
    description: 'City of Pearls and Nizams, famous for Biryani, Charminar, and IT hubs.',
    popularAttractions: ['Charminar', 'Golconda Fort', 'Hussain Sagar Lake', 'Ramoji Film City', 'Salar Jung Museum'],
    image: 'https://images.unsplash.com/photo-1569587112025-0d460e81a126?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Ahmedabad',
    state: 'Gujarat',
    lat: 23.0225,
    lng: 72.5714,
    description: 'UNESCO World Heritage City famed for Gandhi Ashram, textiles, and stepwells.',
    popularAttractions: ['Sabarmati Ashram', 'Adalaj Stepwell', 'Akshardham Gandhinagar', 'Kankaria Lake', 'Sidi Saiyyed Mosque'],
    image: 'https://images.unsplash.com/photo-1563694983011-6f4d90358083?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Pune',
    state: 'Maharashtra',
    lat: 18.5204,
    lng: 73.8567,
    description: 'Cultural capital of Maharashtra, historic seat of the Maratha Empire.',
    popularAttractions: ['Shaniwar Wada', 'Aga Khan Palace', 'Sinhagad Fort', 'Osho Ashram', 'Dagdusheth Halwai Ganpati'],
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd65?auto=format&fit=crop&w=800&q=80',
  },

  // ─── NORTH INDIA ─────────────────────────────────────────────────────────────
  {
    name: 'Agra',
    state: 'Uttar Pradesh',
    lat: 27.1767,
    lng: 78.0081,
    description: 'Home of the timeless Taj Mahal and majestic Mughal architecture.',
    popularAttractions: ['Taj Mahal', 'Agra Fort', 'Fatehpur Sikri', 'Mehtab Bagh', 'Itimad-ud-Daulah'],
    image: 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Varanasi',
    state: 'Uttar Pradesh',
    lat: 25.3176,
    lng: 82.9739,
    description: 'One of the world\'s oldest continuously inhabited sacred spiritual cities along the holy Ganges.',
    popularAttractions: ['Kashi Vishwanath Temple', 'Dashashwamedh Ghat', 'Assi Ghat', 'Manikarnika Ghat', 'Sarnath'],
    image: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Lucknow',
    state: 'Uttar Pradesh',
    lat: 26.8467,
    lng: 80.9462,
    description: 'City of Nawabs celebrated for Awadhi kebabs, courtly etiquettes, and Chikankari embroidery.',
    popularAttractions: ['Bara Imambara', 'Chota Imambara', 'Rumi Darwaza', 'The Residency', 'Hazratganj'],
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099947?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Ayodhya',
    state: 'Uttar Pradesh',
    lat: 26.7922,
    lng: 82.1998,
    description: 'Ancient birthplace of Lord Rama on the banks of holy Sarayu River.',
    popularAttractions: ['Ram Mandir', 'Hanuman Garhi', 'Kanak Bhawan', 'Ram ki Paidi', 'Guptar Ghat'],
    image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Prayagraj (Allahabad)',
    state: 'Uttar Pradesh',
    lat: 25.4358,
    lng: 81.8463,
    description: 'Sacred confluence (Triveni Sangam) of Ganga, Yamuna, and Saraswati rivers, host to Kumbh Mela.',
    popularAttractions: ['Triveni Sangam', 'Allahabad Fort', 'Anand Bhavan', 'Khusro Bagh', 'Alopi Devi Temple'],
    image: 'https://images.unsplash.com/photo-1609620306943-65b57c89f776?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Mathura & Vrindavan',
    state: 'Uttar Pradesh',
    lat: 27.4924,
    lng: 77.6737,
    description: 'Sacred twin pilgrimage towns celebrating the life and leelas of Lord Krishna.',
    popularAttractions: ['Krishna Janmabhoomi', 'Banke Bihari Temple', 'Prem Mandir', 'ISKCON Vrindavan', 'Vishram Ghat'],
    image: 'https://images.unsplash.com/photo-1609946860441-a51ffed7db1f?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Amritsar',
    state: 'Punjab',
    lat: 31.6340,
    lng: 74.8723,
    description: 'Spiritual centre of Sikhism, famous for the Golden Temple and rich Punjabi culinary heritage.',
    popularAttractions: ['Golden Temple', 'Wagah Border', 'Jallianwala Bagh', 'Partition Museum', 'Gobindgarh Fort'],
    image: 'https://images.unsplash.com/photo-1514222134-b57cbb8ce073?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Chandigarh',
    state: 'Chandigarh (UT)',
    lat: 30.7333,
    lng: 76.7794,
    description: 'India\'s first planned city designed by Le Corbusier, famous for modernist architecture and urban greenery.',
    popularAttractions: ['Rock Garden', 'Sukhna Lake', 'Rose Garden', 'Open Hand Monument', 'Elante Mall'],
    image: 'https://images.unsplash.com/photo-1496372412473-e8548ffd82bc?auto=format&fit=crop&w=800&q=80',
  },

  // ─── HIMALAYAN DESTINATIONS ─────────────────────────────────────────────────
  {
    name: 'Shimla',
    state: 'Himachal Pradesh',
    lat: 31.1048,
    lng: 77.1734,
    description: 'Queen of the Hills and former British summer capital with colonial architecture and pine ridges.',
    popularAttractions: ['The Ridge', 'Mall Road', 'Jakhoo Temple', 'Kalka-Shimla Toy Train', 'Viceregal Lodge'],
    image: 'https://images.unsplash.com/photo-1577717903315-1691ae25ab3f?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Manali',
    state: 'Himachal Pradesh',
    lat: 32.2396,
    lng: 77.1887,
    description: 'High-altitude Himalayan hub for adventure sports, snow valleys, and apple orchards.',
    popularAttractions: ['Solang Valley', 'Rohtang Pass', 'Hadimba Temple', 'Old Manali', 'Jogini Waterfall'],
    image: 'https://images.unsplash.com/photo-1584554348797-23a24fcf9a1a?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Dharamshala & McLeod Ganj',
    state: 'Himachal Pradesh',
    lat: 32.2190,
    lng: 76.3234,
    description: 'Seat of the 14th Dalai Lama, Tibetan government in exile, and gateway to the Dhauladhar Range.',
    popularAttractions: ['Tsuglagkhang Complex', 'Bhagsunag Waterfall', 'Triund Trek', 'Namgyal Monastery', 'Dal Lake Dharamshala'],
    image: 'https://images.unsplash.com/photo-1568454537842-d933259bb258?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Rishikesh',
    state: 'Uttarakhand',
    lat: 30.0869,
    lng: 78.2676,
    description: 'Yoga Capital of the World and white-water river rafting hub on the emerald Ganges.',
    popularAttractions: ['Lakshman Jhula', 'Ram Jhula', 'Triveni Ghat Aarti', 'The Beatles Ashram', 'Shivpuri Rafting'],
    image: 'https://images.unsplash.com/photo-1625750305497-d56a9da13f76?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Haridwar',
    state: 'Uttarakhand',
    lat: 29.9457,
    lng: 78.1642,
    description: 'Gateway to the Gods and revered Ganga pilgrimage town hosting the grand Har Ki Pauri Aarti.',
    popularAttractions: ['Har Ki Pauri', 'Mansa Devi Temple', 'Chandi Devi Temple', 'Maya Devi Temple', 'Daksh Prajapati Temple'],
    image: 'https://images.unsplash.com/photo-1628172828699-e60d5ed703c2?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Nainital',
    state: 'Uttarakhand',
    lat: 29.3919,
    lng: 79.4542,
    description: 'Charming lake resort town in Kumaon hills centered around the emerald Naini Lake.',
    popularAttractions: ['Naini Lake', 'Naina Devi Temple', 'Snow View Point', 'Tiffin Top', 'Eco Cave Gardens'],
    image: 'https://images.unsplash.com/photo-1627301518070-7e19cb9a4c96?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Mussoorie',
    state: 'Uttarakhand',
    lat: 30.4598,
    lng: 78.0644,
    description: 'The Queen of Hills overlooking the Doon Valley and Shivalik ranges.',
    popularAttractions: ['Kempty Falls', 'Gun Hill', 'Camel\'s Back Road', 'Lal Tibba', 'Company Garden'],
    image: 'https://images.unsplash.com/photo-1590012314607-cda9d9b699ae?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Srinagar',
    state: 'Jammu & Kashmir',
    lat: 34.0837,
    lng: 74.7973,
    description: 'Paradise on Earth famed for tranquil Dal Lake houseboats, Mughal gardens, and Shikaras.',
    popularAttractions: ['Dal Lake', 'Shalimar Bagh', 'Nishat Bagh', 'Shankaracharya Temple', 'Tulip Garden'],
    image: 'https://images.unsplash.com/photo-1548013146-72479768badb?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Gulmarg',
    state: 'Jammu & Kashmir',
    lat: 34.0484,
    lng: 74.3805,
    description: 'Meadow of Flowers and premier winter skiing resort with the world\'s highest cable car.',
    popularAttractions: ['Gulmarg Gondola', 'Apharwat Peak', 'Golf Course', 'Alpather Lake', 'St. Mary\'s Church'],
    image: 'https://images.unsplash.com/photo-1547059545-6c29e9b7c38e?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Leh-Ladakh',
    state: 'Ladakh (UT)',
    lat: 34.1526,
    lng: 77.5771,
    description: 'Land of High Passes with Tibetan Buddhist monasteries and azure lakes.',
    popularAttractions: ['Pangong Lake', 'Nubra Valley', 'Khardung La Pass', 'Thiksey Monastery', 'Magnetic Hill'],
    image: 'https://images.unsplash.com/photo-1485841890310-6a055c88698a?auto=format&fit=crop&w=800&q=80',
  },

  // ─── RAJASTHAN ───────────────────────────────────────────────────────────────
  {
    name: 'Jaipur',
    state: 'Rajasthan',
    lat: 26.9124,
    lng: 75.7873,
    description: 'The Pink City and royal capital of Rajasthan filled with palaces, forts, and gems.',
    popularAttractions: ['Amber Fort', 'Hawa Mahal', 'City Palace', 'Jantar Mantar', 'Nahargarh Fort', 'Jal Mahal'],
    image: 'https://images.unsplash.com/photo-1578469645742-46cae010e5d4?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Udaipur',
    state: 'Rajasthan',
    lat: 24.5854,
    lng: 73.7125,
    description: 'The City of Lakes and Venice of the East, famed for floating palaces and romance.',
    popularAttractions: ['City Palace', 'Lake Pichola', 'Jag Mandir', 'Fateh Sagar Lake', 'Saheliyon ki Bari'],
    image: 'https://images.unsplash.com/photo-1568454537842-d933259bb259?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Jodhpur',
    state: 'Rajasthan',
    lat: 26.2389,
    lng: 73.0243,
    description: 'The Blue City and Sun City anchored by the mighty Mehrangarh Fort.',
    popularAttractions: ['Mehrangarh Fort', 'Jaswant Thada', 'Umaid Bhawan Palace', 'Clock Tower & Sardar Market', 'Mandore Gardens'],
    image: 'https://images.unsplash.com/photo-1524598222797-b9c167a89e3b?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Jaisalmer',
    state: 'Rajasthan',
    lat: 26.9157,
    lng: 70.9083,
    description: 'The Golden City in the heart of the Great Thar Desert with a living fort.',
    popularAttractions: ['Jaisalmer Fort', 'Sam Sand Dunes', 'Patwon ki Haveli', 'Gadisar Lake', 'Desert National Park'],
    image: 'https://images.unsplash.com/photo-1548013146-72479768badc?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Pushkar & Ajmer',
    state: 'Rajasthan',
    lat: 26.4897,
    lng: 74.5511,
    description: 'Sacred desert lake town with the world\'s only prominent Brahma Temple and Ajmer Sharif Dargah.',
    popularAttractions: ['Brahma Temple', 'Pushkar Lake Ghats', 'Ajmer Sharif Dargah', 'Savitri Temple', 'Camel Fair Grounds'],
    image: 'https://images.unsplash.com/photo-1609620306943-65b57c89f777?auto=format&fit=crop&w=800&q=80',
  },

  // ─── GOA & WEST COAST ───────────────────────────────────────────────────────
  {
    name: 'Goa (Panaji & Beaches)',
    state: 'Goa',
    lat: 15.2993,
    lng: 74.1240,
    description: 'India\'s premier beach destination blending Portuguese heritage, nightlife, and tropical coastline.',
    popularAttractions: ['Baga Beach', 'Calangute Beach', 'Basilica of Bom Jesus', 'Fort Aguada', 'Dudhsagar Falls', 'Palolem Beach'],
    image: 'https://images.unsplash.com/photo-1614082242765-7c98ca0f3df3?auto=format&fit=crop&w=800&q=80',
  },

  // ─── SOUTH INDIA / KERALA & TAMIL NADU ──────────────────────────────────────
  {
    name: 'Kochi (Cochin)',
    state: 'Kerala',
    lat: 9.9312,
    lng: 76.2673,
    description: 'Queen of the Arabian Sea with Portuguese, Dutch, British, and Chinese maritime legacy.',
    popularAttractions: ['Fort Kochi', 'Chinese Fishing Nets', 'Mattancherry Palace', 'Jewish Synagogue', 'Marine Drive'],
    image: 'https://images.unsplash.com/photo-1583987862072-3e01d55e5c61?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Munnar',
    state: 'Kerala',
    lat: 10.0889,
    lng: 77.0595,
    description: 'Verdant hill station enveloped in emerald green rolling tea plantations and mist.',
    popularAttractions: ['Tea Gardens', 'Eravikulam National Park', 'Mattupetty Dam', 'Anamudi Peak', 'Top Station'],
    image: 'https://images.unsplash.com/photo-1535925191578-a5c91b4a2e1e?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Alleppey (Alappuzha)',
    state: 'Kerala',
    lat: 9.4981,
    lng: 76.3388,
    description: 'Venice of the East, famous for tranquil backwater cruises on traditional houseboats.',
    popularAttractions: ['Vembanad Lake', 'Alleppey Backwaters', 'Alappuzha Beach', 'Marari Beach', 'Pathiramanal Island'],
    image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9947?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Mysuru (Mysore)',
    state: 'Karnataka',
    lat: 12.2958,
    lng: 76.6394,
    description: 'City of Palaces, royal heritage, sandalwood, silk sarees, and grand Dasara festivities.',
    popularAttractions: ['Mysore Palace', 'Chamundi Hill', 'Brindavan Gardens', 'St. Philomena\'s Cathedral', 'Devaraja Market'],
    image: 'https://images.unsplash.com/photo-1604537529428-15bcbeecfe4d?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Hampi',
    state: 'Karnataka',
    lat: 15.3350,
    lng: 76.4600,
    description: 'UNESCO World Heritage Site with monumental ruins of the 14th-century Vijayanagara Empire.',
    popularAttractions: ['Virupaksha Temple', 'Vittala Temple Stone Chariot', 'Lotus Mahal', 'Matanga Hill', 'Elephant Stables'],
    image: 'https://images.unsplash.com/photo-1590012314607-cda9d9b699af?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Madurai',
    state: 'Tamil Nadu',
    lat: 9.9252,
    lng: 78.1198,
    description: 'Athens of the East, an ancient temple city built around the towering Meenakshi Amman Temple.',
    popularAttractions: ['Meenakshi Amman Temple', 'Thirumalai Nayakkar Palace', 'Gandhi Memorial Museum', 'Koodal Azhagar Temple'],
    image: 'https://images.unsplash.com/photo-1608036080824-2aeb9ab4fbf9?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Pondicherry (Puducherry)',
    state: 'Puducherry (UT)',
    lat: 11.9416,
    lng: 79.8083,
    description: 'French Riviera of the East with mustard-yellow colonial mansions, chic cafes, and Auroville.',
    popularAttractions: ['Promenade Beach', 'Auroville Matrimandir', 'Sri Aurobindo Ashram', 'French Quarter (White Town)', 'Paradise Beach'],
    image: 'https://images.unsplash.com/photo-1617219764819-9b12a14df0b8?auto=format&fit=crop&w=800&q=80',
  },

  // ─── EAST & NORTH-EAST INDIA ────────────────────────────────────────────────
  {
    name: 'Darjeeling',
    state: 'West Bengal',
    lat: 27.0410,
    lng: 88.2663,
    description: 'Queen of the Hills in the Eastern Himalayas, world-famous for champagne black tea and Kanchenjunga views.',
    popularAttractions: ['Tiger Hill Sunrise', 'Batasia Loop', 'Darjeeling Himalayan Railway', 'Himalayan Mountaineering Institute', 'Happy Valley Tea Estate'],
    image: 'https://images.unsplash.com/photo-1564706649554-98cdee9b2f8e?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Gangtok',
    state: 'Sikkim',
    lat: 27.3389,
    lng: 88.6065,
    description: 'Clean, peaceful capital of Sikkim with Tibetan Buddhist culture and views of Mt. Kanchenjunga.',
    popularAttractions: ['MG Marg', 'Rumtek Monastery', 'Tsomgo Lake', 'Nathu La Pass', 'Enchey Monastery'],
    image: 'https://images.unsplash.com/photo-1610641818989-c2051b5e2cfd?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Shillong & Cherrapunji',
    state: 'Meghalaya',
    lat: 25.5788,
    lng: 91.8933,
    description: 'Scotland of the East with dramatic waterfalls, living root bridges, and lush cloud-kissed plateaus.',
    popularAttractions: ['Double Decker Living Root Bridge', 'Nohkalikai Falls', 'Elephant Falls', 'Umiam Lake', 'Mawsmai Cave', 'Dawki River'],
    image: 'https://images.unsplash.com/photo-1601778083811-6b5e1d4b0e76?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Puri & Konark',
    state: 'Odisha',
    lat: 19.8135,
    lng: 85.8312,
    description: 'Sacred coastal Char Dham abode of Lord Jagannath and the 13th-century Konark Sun Temple.',
    popularAttractions: ['Jagannath Temple', 'Konark Sun Temple', 'Golden Beach', 'Chilika Lake', 'Raghurajpur Heritage Village'],
    image: 'https://images.unsplash.com/photo-1601978236756-67d9c4bd9d01?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Port Blair & Havelock (Swaraj Dweep)',
    state: 'Andaman & Nicobar (UT)',
    lat: 11.6234,
    lng: 92.7265,
    description: 'Tropical island paradise with coral reefs, turquoise lagoons, and the historic Cellular Jail.',
    popularAttractions: ['Radhanagar Beach', 'Cellular Jail', 'Elephant Beach Snorkeling', 'Ross Island', 'Neil Island (Shaheed Dweep)'],
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3a?auto=format&fit=crop&w=800&q=80',
  }
];

export interface PresetTripImage {
  label: string;
  url: string;
}

export const PRESET_TRIP_IMAGES: PresetTripImage[] = [
  { label: 'Taj Mahal & Heritage', url: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80' },
  { label: 'Himalayan Mountain Escape', url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=800&q=80' },
  { label: 'Tropical Goa Coastline', url: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80' },
  { label: 'Rajasthan Desert Dunes', url: 'https://images.unsplash.com/photo-1586861256632-1eb856df2dbc?auto=format&fit=crop&w=800&q=80' },
  { label: 'Kerala Backwaters Houseboat', url: 'https://images.unsplash.com/photo-1569096651661-820d59a91524?auto=format&fit=crop&w=800&q=80' },
  { label: 'Spiritual Varanasi Ghats', url: 'https://images.unsplash.com/photo-1561361058-c24cecae35ca?auto=format&fit=crop&w=800&q=80' },
  { label: 'Golden Temple Amritsar', url: 'https://images.unsplash.com/photo-1609946860441-a51ffed7db1e?auto=format&fit=crop&w=800&q=80' },
  { label: 'Lakes of Udaipur', url: 'https://images.unsplash.com/photo-1615836245337-f5b9b2303f10?auto=format&fit=crop&w=800&q=80' },
  { label: 'Ladakh High Mountain Passes', url: 'https://images.unsplash.com/photo-1513094775335-7f3bc4e3e0e8?auto=format&fit=crop&w=800&q=80' }
];

export default INDIAN_CITIES;
