"use client";

import { useState } from "react";
import { Trip } from "@/lib/models";
import { cities } from "@/lib/data";

export default function ExportModal({
  trip,
  isOpen,
  onClose,
}: {
  trip: Trip;
  isOpen: boolean;
  onClose: () => void;
}) {
  const [copiedMd, setCopiedMd] = useState(false);
  const [copiedLink, setCopiedLink] = useState(false);

  if (!isOpen) return null;

  // Generate clean Markdown itinerary
  const generateMarkdown = () => {
    let md = `# ${trip.name}\n\n`;
    md += `> **Dates**: ${trip.dates} | **Budget**: ₹${trip.budget.toLocaleString("en-IN")}\n\n`;

    md += `## Destinations & Stops\n`;
    trip.stops.forEach((stop, idx) => {
      const city = cities.find((c) => c.id === stop.cityId);
      md += `${idx + 1}. **${city?.name || stop.cityId}** (${city?.state || ""}) - ${stop.date}\n`;
    });
    md += `\n`;

    if (trip.itinerary && trip.itinerary.length > 0) {
      md += `## Schedule & Activities\n\n`;
      trip.itinerary.forEach((item) => {
        md += `- **${item.time}** - ${item.title} (${item.location || "Local"}) · Duration: ${item.duration}${item.cost ? ` · Est. ₹${item.cost}` : ""}\n`;
      });
      md += `\n`;
    }

    if (trip.expenses.length > 0) {
      md += `## Planned Expenses\n`;
      let total = 0;
      trip.expenses.forEach((e) => {
        total += e.amount;
        md += `- ${e.category}: ₹${e.amount.toLocaleString("en-IN")}\n`;
      });
      md += `\n**Total Estimated Spend**: ₹${total.toLocaleString("en-IN")}\n\n`;
    }

    md += `---\n*Generated by BharatYatra — Personalized India Travel Planner*\n`;
    return md;
  };

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(generateMarkdown());
    setCopiedMd(true);
    setTimeout(() => setCopiedMd(false), 2000);
  };

  const handleDownloadMarkdown = () => {
    const md = generateMarkdown();
    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${trip.name.toLowerCase().replace(/[^a-z0-9]/g, "-")}-itinerary.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleCopyLink = () => {
    const origin = typeof window !== "undefined" ? window.location.origin : "";
    const shareUrl = `${origin}/shared/${trip.id}`;
    navigator.clipboard.writeText(shareUrl);
    setCopiedLink(true);
    setTimeout(() => setCopiedLink(false), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div
      style={{
        position: "fixed",
        inset: 0,
        zIndex: 9999,
        background: "rgba(9, 14, 23, 0.7)",
        backdropFilter: "blur(8px)",
        WebkitBackdropFilter: "blur(8px)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        padding: "20px",
      }}
      onClick={onClose}
    >
      <div
        style={{
          width: "100%",
          maxWidth: "540px",
          background: "var(--surface)",
          border: "1px solid var(--border)",
          borderRadius: "var(--radius-2xl)",
          boxShadow: "0 25px 50px -12px rgba(0, 0, 0, 0.35)",
          padding: "28px",
        }}
        onClick={(e) => e.stopPropagation()}
      >
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: "16px" }}>
          <div>
            <span className="eyebrow">SHARE & EXPORT</span>
            <h3 style={{ fontSize: "20px", fontWeight: 700, margin: "4px 0 0" }}>
              Export {trip.name}
            </h3>
          </div>
          <button
            onClick={onClose}
            style={{
              background: "var(--surface-alt)",
              border: "1px solid var(--border)",
              borderRadius: "50%",
              width: "32px",
              height: "32px",
              cursor: "pointer",
              fontSize: "14px",
              color: "var(--ink-600)",
            }}
          >
            ✕
          </button>
        </div>

        <p style={{ fontSize: "14px", color: "var(--ink-600)", marginBottom: "24px", lineHeight: 1.5 }}>
          Take your itinerary offline, print a paper-friendly schedule, or share a read-only live link with your travel partners.
        </p>

        <div style={{ display: "flex", flexDirection: "column", gap: "14px" }}>
          {/* Print / Save to PDF */}
          <div
            style={{
              display: "flex",
              alignItems: "center",
              justifyContent: "space-between",
              padding: "16px",
              background: "var(--surface-alt)",
              borderRadius: "var(--radius-xl)",
              border: "1px solid var(--border)",
            }}
          >
            <div>
              <strong style={{ display: "block", fontSize: "15px", color: "var(--ink-900)" }}>
                🖨️ Print or Save as PDF
              </strong>
              <span style={{ fontSize: "12.5px", color: "var(--ink-500)" }}>
                High-contrast, clean format without navbars or ads
              </span>
            </div>
            <button onClick={handlePrint} className="btn btn-outline btn-sm">
              Print / PDF
            </button>
          </div>

          {/* Download Markdown */}
          <div
            style={{
              display: "flex",
              alignItems: "center",
              justifyContent: "space-between",
              padding: "16px",
              background: "var(--surface-alt)",
              borderRadius: "var(--radius-xl)",
              border: "1px solid var(--border)",
            }}
          >
            <div>
              <strong style={{ display: "block", fontSize: "15px", color: "var(--ink-900)" }}>
                📄 Markdown Note (.md)
              </strong>
              <span style={{ fontSize: "12.5px", color: "var(--ink-500)" }}>
                Compatible with Notion, Apple Notes, and Obsidian
              </span>
            </div>
            <div style={{ display: "flex", gap: "8px" }}>
              <button onClick={handleCopyMarkdown} className="btn btn-ghost btn-sm" style={{ border: "1px solid var(--border)" }}>
                {copiedMd ? "✓ Copied" : "Copy"}
              </button>
              <button onClick={handleDownloadMarkdown} className="btn btn-primary btn-sm">
                Download
              </button>
            </div>
          </div>

          {/* Copy Public Link */}
          <div
            style={{
              display: "flex",
              alignItems: "center",
              justifyContent: "space-between",
              padding: "16px",
              background: "var(--surface-alt)",
              borderRadius: "var(--radius-xl)",
              border: "1px solid var(--border)",
            }}
          >
            <div>
              <strong style={{ display: "block", fontSize: "15px", color: "var(--ink-900)" }}>
                🔗 Public Share Link
              </strong>
              <span style={{ fontSize: "12.5px", color: "var(--ink-500)" }}>
                Read-only link with 1-click &ldquo;Clone to My Trips&rdquo;
              </span>
            </div>
            <button onClick={handleCopyLink} className="btn btn-outline btn-sm">
              {copiedLink ? "✓ Copied Link" : "Copy Link"}
            </button>
          </div>
        </div>

        <div style={{ marginTop: "24px", textAlign: "right" }}>
          <button onClick={onClose} className="btn btn-ghost btn-sm">
            Done
          </button>
        </div>
      </div>
    </div>
  );
}
